### ISSUE TITLE
updating timm dependency

### ISSUE THREAD

**Issue by aravindhv10** [huggingface/controlnet_aux#106]
Hi, I noticed that the version of timm used in latest version of controlnet_aux is old (<=0.6.7). I want to use controlnet_aux with transparent_background (https://github.com/plemeri/transparent-background) but this requires a newer version of timm (>=0.6.11). So wanted to know what is keeping controlnet_aux from using the newer version of timm and can I help with porting some of this code?

**Comment by asomoza** [comment]
Hi, that was added because the Zoe depth didn’t work with the newer ones. If you want to take a look into it, we would be more than happy to review a PR.

**Comment by aravindhv10** [comment]
ok thanks, will try.
