### ISSUE TITLE
`Failed to find C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel/Annotators\150_16_swin_l_oneformer_coco_100ep.pth.

### ISSUE THREAD

**Issue by gigi-wins** [huggingface/controlnet_aux#107]
Hi,

I'm trying to use this workflow: https://civitai.com/models/420317?modelVersionId=468375

All Missing Nodes successfully installed via. ComfyUI Manager

I still got this Error.

`Failed to find C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel/Annotators\150_16_swin_l_oneformer_coco_100ep.pth.
 Downloading from huggingface.co
cacher folder is C:\Users\Gianluca\AppData\Local\Temp, you can change it by custom_tmp_path in config.yaml
C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py:1194: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
!!! Exception during processing!!! [Errno 2] No such file or directory: 'C:\\Users\\Gianluca\\Downloads\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\lllyasviel\\Annotators\\.huggingface\\download\\150_16_swin_l_oneformer_coco_100ep.pth.0684dfc39720c772b81d43639c3ae1896b5c15aa9ee9a76f4c593b19dfa33855.incomplete'
Traceback (most recent call last):
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\oneformer.py", line 17, in semantic_segmentate
    model = OneformerSegmentor.from_pretrained(filename="150_16_swin_l_oneformer_coco_100ep.pth")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\oneformer\__init__.py", line 32, in from_pretrained
    model_path = custom_hf_download(pretrained_model_or_path, filename)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py", line 324, in custom_hf_download
    model_path = hf_hub_download(repo_id=pretrained_model_or_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1202, in hf_hub_download
    return _hf_hub_download_to_local_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1487, in _hf_hub_download_to_local_dir
    _download_to_tmp_and_move(
  File "C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1872, in _download_to_tmp_and_move
    with incomplete_path.open("ab") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Gianluca\\Downloads\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\lllyasviel\\Annotators\\.huggingface\\download\\150_16_swin_l_oneformer_coco_100ep.pth.0684dfc39720c772b81d43639c3ae1896b5c15aa9ee9a76f4c593b19dfa33855.incomplete'`

I manually downloaded https://huggingface.co/lllyasviel/Annotators/blob/main/150_16_swin_l_oneformer_coco_100ep.pth and put it in ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\lllyasviel\\Annotators\\.huggingface\\download\\ (since it was empty), but it still doenst work. 

I tried a lot random stuff with chatGPT, but still not working.

Re-installing and repeating only the most necessary steps -> still not working.

THank you.

BR

Gianluca

**Comment by asomoza** [comment]
Hi, this repo is for diffusers, you need to report this is the correct comfyui one.

**Comment by gigi-wins** [comment]
I think I fixed it, thanks to chatgpt.

This file  https://huggingface.co/lllyasviel/Annotators/blob/main/150_16_swin_l_oneformer_coco_100ep.pth 

shall be put into "\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel\Annotators\150_16_swin_l_oneformer_coco_100ep.pth"

and NOT into 

"C:\Users\Gianluca\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel\Annotators\.huggingface\download\150_16_swin_l_oneformer_coco_100ep.pth"

also adjust config.yaml in confyui_controlnet_aux

annotator_ckpts_path: "C:\\Users\\Gianluca\\Downloads\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts"
